# Makefile
.PHONY: test test-int build lint ci build-plugin lint-plugin test-plugin
test:         ; go test ./...
test-int:     ; go test -tags=integration ./...
build:        ; go build ./...
lint:         ; go vet ./...
build-plugin: ; cd plugin/promhash-datasource && go build ./...
lint-plugin:  ; cd plugin/promhash-datasource && go vet ./...
test-plugin:  ; cd plugin/promhash-datasource && go test ./...
ci: build lint test build-plugin lint-plugin test-plugin
