# Makefile
.PHONY: test test-int build lint ci build-plugin lint-plugin test-plugin dist-plugin
test:         ; go test ./...
test-int:     ; go test -tags=integration ./...
build:        ; go build ./...
lint:         ; go vet ./...
build-plugin: ; cd plugin/promhash-datasource && go build ./...
lint-plugin:  ; cd plugin/promhash-datasource && go vet ./...
test-plugin:  ; cd plugin/promhash-datasource && go test ./... && npx tsc --noEmit
# Deployable plugin artifact: frontend bundle + plugin.json + linux backend binaries in dist/.
dist-plugin:
	cd plugin/promhash-datasource && npm run build && \
	GOOS=linux GOARCH=amd64 go build -o dist/gpx_promhash_linux_amd64 ./pkg && \
	GOOS=linux GOARCH=arm64 go build -o dist/gpx_promhash_linux_arm64 ./pkg
ci: build lint test build-plugin lint-plugin test-plugin
